# Generated by Django 5.2.16 on 2026-08-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('profile_image', models.TextField(blank=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20)),
                ('contact_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('enrolled_date', models.DateField(blank=True, null=True)),
                ('session_year', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
