# Generated by Django 5.2.16 on 2026-08-03 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('research_document', models.FileField(blank=True, null=True, upload_to='research_documents/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.CharField(max_length=20)),
                ('beneficiary_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher_role', models.CharField(choices=[('senior', 'Senior Researcher'), ('junior', 'Junior Researcher'), ('assistant', 'Research Assistant')], max_length=30)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to='research.research')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('research', 'user')},
            },
        ),
    ]
